### ISSUE TITLE
UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by FilipLitwora** [macias100/quizizz-hack#5]
Console output some time after `!noclass <code> `

```
(node:7143) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded
    at /home/filip/quizizz-hack/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
    at async FrameManager.waitForFrameNavigation (/home/filip/quizizz-hack/node_modules/puppeteer/lib/FrameManager.js:139:19)
    at async Frame.waitForNavigation (/home/filip/quizizz-hack/node_modules/puppeteer/lib/FrameManager.js:414:12)
    at async Page.waitForNavigation (/home/filip/quizizz-hack/node_modules/puppeteer/lib/Page.js:692:12)
    at async /home/filip/quizizz-hack/index.js:75:9
  -- ASYNC --
    at Frame.<anonymous> (/home/filip/quizizz-hack/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.waitForNavigation (/home/filip/quizizz-hack/node_modules/puppeteer/lib/Page.js:692:49)
    at Page.<anonymous> (/home/filip/quizizz-hack/node_modules/puppeteer/lib/helper.js:112:23)
    at /home/filip/quizizz-hack/index.js:75:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7143) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7143) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by macias100** [comment]
Commited new version, if this one won't be working, add me on discord: Macias#7761
